"""add rediscovery email preference

Revision ID: 4d75d74bf837
Revises: b6d09303e9e1
Create Date: 2026-10-07 20:43:26.572364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d75d74bf837'
down_revision: Union[str, Sequence[str], None] = 'b6d09303e9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rediscovery_emails_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rediscovery_emails_enabled')
    # ### end Alembic commands ###
