"""add last accessed timestamp

Revision ID: 8497b0041668
Revises: dafd0f25c538
Create Date: 2026-10-03 12:31:17.965699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8497b0041668'
down_revision: Union[str, Sequence[str], None] = 'dafd0f25c538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'last_accessed_at')
    # ### end Alembic commands ###
