"""add rediscovery email timestamp

Revision ID: 8d47d51980e7
Revises: dade3b946fe9
Create Date: 2026-10-04 20:37:46.668196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d47d51980e7'
down_revision: Union[str, Sequence[str], None] = 'dade3b946fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_rediscovery_email_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_rediscovery_email_at')
    # ### end Alembic commands ###
