"""add is_favorite to resources

Revision ID: b6d09303e9e1
Revises: 14791efd9a85
Create Date: 2026-10-06 19:07:41.661738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d09303e9e1'
down_revision: Union[str, Sequence[str], None] = '14791efd9a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'is_favorite')
    # ### end Alembic commands ###
