"""add collection to resources

Revision ID: c128372e1220
Revises: 695dca718542
Create Date: 2026-09-28 11:00:28.550151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c128372e1220'
down_revision: Union[str, Sequence[str], None] = '695dca718542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_resources_collection_id'), 'resources', ['collection_id'], unique=False)
    op.create_foreign_key(None, 'resources', 'collections', ['collection_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_index(op.f('ix_resources_collection_id'), table_name='resources')
    op.drop_column('resources', 'collection_id')
    # ### end Alembic commands ###
